"use client";

import Toolbar from "@/app/toolbar/toolbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import store from "@/store/store";
import { Provider, useSelector } from "react-redux";
import { Fragment } from "react";
import { Load } from "@/models/interface";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Daily Nexus",
  description: "Generated by create next app",
};

const PageWithRedux = ({ children }: { children: React.ReactNode }) => {

  const load = useSelector((state: Load) => state.load.loader);
  return (
    <Fragment>
      <Toolbar />
      <div className={load ? "pointer-events-none opacity-40" : undefined}>{children}</div>
      <ToastContainer />
    </Fragment>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <PageWithRedux>{children}</PageWithRedux>
        </Provider>
      </body>
    </html>
  );
}
