
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import store from "@/store/store";
import { Provider } from "react-redux";
import MainPage from "./Home";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Daily Nexus",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <MainPage>{children}</MainPage>
        </Provider>
      </body>
    </html>
  );
}

